package com.sdingba.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sdingba.entity.AdPosition;
import com.sdingba.entity.AdPositionExample;



public interface AdPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_position
     *
     * @mbggenerated
     */
    int countByExample(AdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_position
     *
     * @mbggenerated
     */
    int deleteByExample(AdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_position
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_position
     *
     * @mbggenerated
     */
    int insert(AdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_position
     *
     * @mbggenerated
     */
    int insertSelective(AdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_position
     *
     * @mbggenerated
     */
    List<AdPosition> selectByExample(AdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_position
     *
     * @mbggenerated
     */
    AdPosition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_position
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AdPosition record, @Param("example") AdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_position
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AdPosition record, @Param("example") AdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_position
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_position
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdPosition record);
}