server:
    port: 8080
spring:
    datasource:
        name: crm
        url: jdbc:mysql://127.0.0.1:3306/crm
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 1
        maxActive: 50
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        connection-timeout: 2000
        connection-properties: druid.stat.slowSqlMillis=200
    aop:
        auto: true
#mybatis:
#  typeAliasesPackage: com.huitui.com.sdingba.entity
#  mapper-locations: classpath:mybatis/*.xml
mybatis:
  typeAliasesPackage: com.sdingba.entity
  mapper-locations: classpath:mybatis/*.xml
  configLocation: classpath:/mybatis-config.xml